language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
install:
  - pip install coveralls
script:
  - python -m compileall -f .
  - coverage run --source=kwonly_args setup.py test
after_success:
  coveralls
notifications:
  email: false
